/**
 * Report Formatter Service
 *
 * Formats PR diff changed symbols and downstream impact analysis results
 * into a GitHub PR comment markdown body.
 */

/**
 * Format confidence badge with emoji and relation type
 */
function formatConfidence(relationType, severity) {
  switch (relationType) {
    case "direct_call":
      return "🔴 High (direct_call)";
    case "transitive_call":
      return "🟡 Medium (transitive_call)";
    case "semantic":
      return "⚪ Low (semantic)";
    default:
      return `${severity || "Unknown"} (${relationType})`;
  }
}

const severityOrder = { high: 1, medium: 2, low: 3 };

/**
 * Compare two impact rows by severity (high -> medium -> low),
 * then alphabetically by impacted symbol name.
 */
function compareImpactSeverity(a, b) {
  const orderA = severityOrder[a.severity] || 99;
  const orderB = severityOrder[b.severity] || 99;
  if (orderA !== orderB) return orderA - orderB;

  const nameA =
    a.impacted_symbol_name ||
    a.impacted_symbol?.symbol_name ||
    "";
  const nameB =
    b.impacted_symbol_name ||
    b.impacted_symbol?.symbol_name ||
    "";
  return nameA.localeCompare(nameB);
}

/**
 * Check if an impact row belongs to a changed symbol
 */
function impactMatchesSymbol(impact, symbol) {
  if (symbol.symbol_id != null && impact.source_symbol_id != null) {
    return impact.source_symbol_id === symbol.symbol_id;
  }
  const sourceName = impact.source_symbol?.symbol_name || impact.source_symbol_name;
  const sourcePath =
    impact.source_symbol?.file_path ||
    impact.source_file_path ||
    impact.source_symbol?.file?.file_path;
  return (
    Boolean(sourceName) &&
    sourceName === symbol.symbol_name &&
    Boolean(sourcePath) &&
    sourcePath === symbol.file_path
  );
}

/**
 * Group and sort impacts by source symbol, and severity within each group
 */
function groupAndSortImpacts(changedSymbols = [], impactRows = []) {
  const result = [];
  const handledImpacts = new Set();

  for (const symbol of changedSymbols) {
    const matches = [];
    for (const imp of impactRows) {
      if (impactMatchesSymbol(imp, symbol)) {
        matches.push(imp);
        handledImpacts.add(imp);
      }
    }

    matches.sort(compareImpactSeverity);
    result.push(...matches);
  }

  // Any impacts that did not match a changed symbol (edge case)
  const remaining = impactRows.filter((imp) => !handledImpacts.has(imp));
  if (remaining.length > 0) {
    remaining.sort(compareImpactSeverity);
    result.push(...remaining);
  }

  return result;
}

/**
 * Format changed symbols and impact rows into GitHub PR comment markdown
 *
 * @param {Object} params
 * @param {Array<Object>} params.changedSymbols - Symbols touched by PR diff
 * @param {Array<Object>} params.impactRows - Downstream impact rows from analyzeImpact()
 * @returns {string} Formatted markdown string
 */
function formatImpactReportMarkdown({ changedSymbols = [], impactRows = [] }) {
  const lines = [];

  // 1. Header
  lines.push("## 🔍 GitRAG Impact Analysis\n");

  // Calculate summary counts
  const directCount = impactRows.filter((r) => r.relation_type === "direct_call").length;
  const transitiveCount = impactRows.filter((r) => r.relation_type === "transitive_call").length;
  const semanticCount = impactRows.filter((r) => r.relation_type === "semantic").length;
  const totalImpacts = impactRows.length;
  const changedCount = changedSymbols.length;

  // 2. One-line summary
  lines.push(
    `Found **${totalImpacts}** downstream impact(s) across **${changedCount}** changed symbol(s): ` +
    `**${directCount}** direct dependencies, **${transitiveCount}** transitive dependencies, **${semanticCount}** semantically related — unconfirmed.\n`
  );

  // 3. Group impacts by source changed symbol
  for (const symbol of changedSymbols) {
    lines.push(`### \`${symbol.symbol_name}\` (${symbol.change_type}) — \`${symbol.file_path}\`\n`);

    // Match impacts for this changed symbol
    const matches = impactRows.filter((imp) => impactMatchesSymbol(imp, symbol));

    if (matches.length === 0) {
      lines.push("No downstream impacts detected for this symbol.\n");
      continue;
    }

    // Sort rows within symbol's table by severity (high -> medium -> low)
    matches.sort(compareImpactSeverity);

    // Render markdown table
    lines.push("| Confidence | Symbol | File | Reason |");
    lines.push("| :--- | :--- | :--- | :--- |");

    for (const row of matches) {
      const confidence = formatConfidence(row.relation_type, row.severity);
      const sym = `\`${row.impacted_symbol_name || row.impacted_symbol?.symbol_name}\``;
      const file = `\`${row.impacted_file_path || row.impacted_symbol?.file?.file_path || row.impacted_symbol?.file_path}\``;
      const reason = row.reason.replace(/\|/g, "\\|");
      lines.push(`| ${confidence} | ${sym} | ${file} | ${reason} |`);
    }

    lines.push(""); // blank line
  }

  // 4. Closing disclaimer line
  lines.push(
    "*Generated by GitRAG — direct/transitive results are based on static call-graph analysis; semantic results are unconfirmed and may include false positives.*"
  );

  return lines.join("\n");
}

module.exports = {
  formatImpactReportMarkdown,
  compareImpactSeverity,
  impactMatchesSymbol,
  groupAndSortImpacts
};

