/**
 * Report Formatter Service
 *
 * Formats PR diff changed symbols and downstream impact analysis results
 * into a GitHub PR comment markdown body.
 */

/**
 * Format confidence badge with emoji and relation type
 */
function formatConfidence(relationType, severity) {
  switch (relationType) {
    case "direct_call":
      return "🔴 High (direct_call)";
    case "transitive_call":
      return "🟡 Medium (transitive_call)";
    case "semantic":
      return "⚪ Low (semantic)";
    default:
      return `${severity || "Unknown"} (${relationType})`;
  }
}

/**
 * Format changed symbols and impact rows into GitHub PR comment markdown
 *
 * @param {Object} params
 * @param {Array<Object>} params.changedSymbols - Symbols touched by PR diff
 * @param {Array<Object>} params.impactRows - Downstream impact rows from analyzeImpact()
 * @returns {string} Formatted markdown string
 */
function formatImpactReportMarkdown({ changedSymbols = [], impactRows = [] }) {
  const lines = [];

  // 1. Header
  lines.push("## 🔍 GitRAG Impact Analysis\n");

  // Calculate summary counts
  const directCount = impactRows.filter((r) => r.relation_type === "direct_call").length;
  const transitiveCount = impactRows.filter((r) => r.relation_type === "transitive_call").length;
  const semanticCount = impactRows.filter((r) => r.relation_type === "semantic").length;
  const totalImpacts = impactRows.length;
  const changedCount = changedSymbols.length;

  // 2. One-line summary
  lines.push(
    `Found **${totalImpacts}** downstream impact(s) across **${changedCount}** changed symbol(s): ` +
    `**${directCount}** direct dependencies, **${transitiveCount}** transitive dependencies, **${semanticCount}** semantically related — unconfirmed.\n`
  );

  // 3. Group impacts by source changed symbol
  const severityOrder = { high: 1, medium: 2, low: 3 };

  for (const symbol of changedSymbols) {
    lines.push(`### \`${symbol.symbol_name}\` (${symbol.change_type}) — \`${symbol.file_path}\`\n`);

    // Match impacts for this changed symbol
    const matches = impactRows.filter((imp) => {
      if (symbol.symbol_id != null && imp.source_symbol_id != null) {
        return imp.source_symbol_id === symbol.symbol_id;
      }
      return (
        imp.source_symbol &&
        imp.source_symbol.symbol_name === symbol.symbol_name &&
        imp.source_symbol.file_path === symbol.file_path
      );
    });

    if (matches.length === 0) {
      lines.push("No downstream impacts detected for this symbol.\n");
      continue;
    }

    // Sort rows within symbol's table by severity (high -> medium -> low)
    matches.sort((a, b) => {
      const orderA = severityOrder[a.severity] || 99;
      const orderB = severityOrder[b.severity] || 99;
      if (orderA !== orderB) return orderA - orderB;
      return (a.impacted_symbol_name || "").localeCompare(b.impacted_symbol_name || "");
    });

    // Render markdown table
    lines.push("| Confidence | Symbol | File | Reason |");
    lines.push("| :--- | :--- | :--- | :--- |");

    for (const row of matches) {
      const confidence = formatConfidence(row.relation_type, row.severity);
      const sym = `\`${row.impacted_symbol_name}\``;
      const file = `\`${row.impacted_file_path}\``;
      const reason = row.reason.replace(/\|/g, "\\|");
      lines.push(`| ${confidence} | ${sym} | ${file} | ${reason} |`);
    }

    lines.push(""); // blank line
  }

  // 4. Closing disclaimer line
  lines.push(
    "*Generated by GitRAG — direct/transitive results are based on static call-graph analysis; semantic results are unconfirmed and may include false positives.*"
  );

  return lines.join("\n");
}

module.exports = {
  formatImpactReportMarkdown
};
